import React from 'react';

// Exact colors matching Flutter AppColors
export const AppColors = {
  orange: '#E8690A',
  orangeLight: '#FEF0E6',
  orangeDark: '#C94E00',
  indigo: '#3D3D8F',
  indigoLight: '#EEEDFE',
  cream: '#FDF8F2',
  white: '#FFFFFF',
  gold: '#F5A623',
  textDark: '#1A1A2E',
  textMid: '#555555',
  textMuted: '#999999',
  border: '#E8E0D8',
  green: '#2D7D46',
  red: '#C0392B',
};

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    width: '100%',
    backgroundColor: AppColors.cream,
    color: AppColors.textDark,
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    borderBottom: `1.5px solid ${AppColors.border}`,
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    padding: '14px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    boxShadow: '0 2px 10px rgba(61, 61, 143, 0.04)',
  },
  brandGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  logoImg: {
    width: '42px',
    height: '42px',
    borderRadius: '10px',
    objectFit: 'contain',
    boxShadow: '0 2px 8px rgba(232, 105, 10, 0.15)',
    backgroundColor: AppColors.white,
    padding: '2px',
    border: `1px solid ${AppColors.border}`,
  },
  brandTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    fontFamily: "'Playfair Display', Georgia, serif",
    color: AppColors.textDark,
    lineHeight: 1.15,
  },
  brandSubtitle: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: AppColors.indigo,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  iconBtn: {
    background: AppColors.white,
    border: `1.5px solid ${AppColors.border}`,
    color: AppColors.textMid,
    borderRadius: '12px',
    padding: '8px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    cursor: 'pointer',
    fontSize: '0.85rem',
    fontWeight: 600,
    fontFamily: "'DM Sans', sans-serif",
    transition: 'all 0.2s ease',
  },
  heroBanner: {
    background: `radial-gradient(ellipse at top center, rgba(232, 105, 10, 0.09) 0%, rgba(253, 248, 242, 0.6) 60%, ${AppColors.cream} 100%)`,
    padding: '48px 24px 36px 24px',
    textAlign: 'center',
    borderBottom: `1.5px solid ${AppColors.border}`,
  },
  heroLogoContainer: {
    width: '84px',
    height: '84px',
    margin: '0 auto 18px auto',
    borderRadius: '22px',
    backgroundColor: AppColors.white,
    padding: '8px',
    border: `1.5px solid ${AppColors.border}`,
    boxShadow: '0 8px 24px rgba(232, 105, 10, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroLogoImg: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 14px',
    borderRadius: '9999px',
    fontSize: '0.8rem',
    fontWeight: 600,
    background: AppColors.orangeLight,
    color: AppColors.orangeDark,
    border: `1px solid rgba(232, 105, 10, 0.25)`,
    marginBottom: '16px',
  },
  heroTitle: {
    fontSize: 'clamp(1.9rem, 4vw, 2.7rem)',
    fontWeight: 700,
    fontFamily: "'Playfair Display', Georgia, serif",
    color: AppColors.textDark,
    marginBottom: '12px',
    letterSpacing: '-0.02em',
  },
  heroSubtitle: {
    fontSize: '1.02rem',
    color: AppColors.textMid,
    maxWidth: '680px',
    margin: '0 auto 18px auto',
    lineHeight: 1.6,
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    flexWrap: 'wrap',
    fontSize: '0.85rem',
    color: AppColors.textMuted,
  },
  contentWrapper: {
    flex: 1,
    maxWidth: '1220px',
    width: '100%',
    margin: '0 auto',
    padding: '40px 24px',
    display: 'grid',
    gridTemplateColumns: '270px 1fr',
    gap: '32px',
    alignItems: 'start',
  },
  tocSidebar: {
    position: 'sticky',
    top: '84px',
    maxHeight: 'calc(100vh - 100px)',
    overflowY: 'auto',
    padding: '18px 14px',
    borderRadius: '16px',
    backgroundColor: AppColors.white,
    border: `1.5px solid ${AppColors.border}`,
    boxShadow: '0 4px 18px rgba(26, 26, 46, 0.03)',
  },
  tocTitle: {
    fontSize: '0.85rem',
    fontFamily: "'Playfair Display', Georgia, serif",
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: AppColors.indigo,
    fontWeight: 700,
    marginBottom: '12px',
    paddingLeft: '8px',
  },
  tocList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    listStyle: 'none',
  },
  tocLink: {
    fontSize: '0.82rem',
    color: AppColors.textMid,
    textDecoration: 'none',
    padding: '7px 10px',
    borderRadius: '10px',
    display: 'block',
    transition: 'all 0.15s ease',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    fontFamily: "'DM Sans', sans-serif",
  },
  mainCard: {
    padding: '40px',
    backgroundColor: AppColors.white,
    borderRadius: '18px',
    border: `1.5px solid ${AppColors.border}`,
    boxShadow: '0 4px 24px rgba(26, 26, 46, 0.04)',
  },
  noticeBox: {
    padding: '18px 22px',
    borderRadius: '14px',
    background: AppColors.indigoLight,
    border: `1.5px solid rgba(61, 61, 143, 0.2)`,
    marginBottom: '36px',
    color: AppColors.textDark,
  },
  section: {
    marginBottom: '42px',
    scrollMarginTop: '100px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '16px',
    borderBottom: `1.5px solid ${AppColors.border}`,
    paddingBottom: '12px',
  },
  sectionNumber: {
    width: '30px',
    height: '30px',
    borderRadius: '10px',
    background: AppColors.orangeLight,
    color: AppColors.orange,
    border: `1px solid rgba(232, 105, 10, 0.25)`,
    fontSize: '0.85rem',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'DM Sans', sans-serif",
    flexShrink: 0,
  },
  sectionTitle: {
    fontSize: '1.28rem',
    fontWeight: 700,
    fontFamily: "'Playfair Display', Georgia, serif",
    color: AppColors.textDark,
  },
  subHeading: {
    fontSize: '1.02rem',
    fontWeight: 600,
    fontFamily: "'Playfair Display', Georgia, serif",
    color: AppColors.indigo,
    marginTop: '20px',
    marginBottom: '10px',
  },
  sectionParagraph: {
    fontSize: '0.94rem',
    lineHeight: 1.72,
    color: AppColors.textMid,
    marginBottom: '14px',
  },
  bulletList: {
    paddingLeft: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '16px',
  },
  bulletItem: {
    fontSize: '0.94rem',
    lineHeight: 1.65,
    color: AppColors.textMid,
  },
  contactGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '16px',
    marginTop: '18px',
  },
  contactCard: {
    padding: '18px',
    borderRadius: '14px',
    background: AppColors.cream,
    border: `1.5px solid ${AppColors.border}`,
  },
  footer: {
    backgroundColor: AppColors.white,
    borderTop: `1.5px solid ${AppColors.border}`,
    padding: '24px 32px',
    textAlign: 'center',
    color: AppColors.textMuted,
    fontSize: '0.85rem',
  },
};
